import type { NextPage } from "next"
// import dynamic from "next/dynamic"
import Head from "next/head"
import TicTacToe from "../components/compositions/TicTacToe"
import { RoomCreator } from "../components/compositions/RoomCreator"
// const TicTacToe = dynamic(() => import('../components/TicTacToe'), {
//   ssr: false,
// })

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Tic Tac Toe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <TicTacToe /> */}
      <RoomCreator />
    </div>
  )
}

export default Home
