import type { NextPage } from 'next'
import Head from 'next/head'
import { useState, MouseEvent } from 'react'

type StateType = '' | 'x' | 'o'
export interface Board {
  state: StateType
}
const initialBoard: Board[] = [
  { state: '' },
  { state: '' },
  { state: '' },
  { state: '' },
  { state: '' },
  { state: '' },
  { state: '' },
  { state: '' },
  { state: '' },
]

const Home: NextPage = () => {
  const [board, setBoard] = useState<Board[]>(initialBoard)
  const [isPlayerOneTurn, setPlayerOneTurn] = useState<boolean>(true)

  function handleClick(index: number) {
    const newBoard = [...board]
    if (newBoard[index].state !== '') return null
    newBoard[index].state = isPlayerOneTurn ? 'x' : 'o'
    setBoard(newBoard)
    setPlayerOneTurn(!isPlayerOneTurn)
  }

  const buttonStyle = `w-full aspect-square border-black border-[1px] text-9xl `
  return (
    <div>
      <Head>
        <title>Tic Tac Toe</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='p-4'>
        <h1 className='text-4xl text-center'>Tic Tac Toe</h1>
        <div className='grid grid-cols-3 p-20 pt-16'>
          {board.map(({ state }, index) => (
            <button
              className={buttonStyle}
              key={index}
              onClick={() => handleClick(index)}
            >
              {state}
            </button>
          ))}
        </div>
      </div>
    </div>
  )
}

export default Home
